# For local dev use - creates a postgres server.  Use "yarn db-start"
version: "3"
services:
  db:
    image: "postgres:11.8"
    container_name: "prisma-admin-pg"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=prisma-admin
    ports:
      - "54320:5432"
